
services:
  app1:
    build: ./app
    environment:
      - HOSTNAME=app-container1
      - PLATFORM=MacOS-Emon

  app2:
    build: ./app
    environment:
      - HOSTNAME=app-container2
      - PLATFORM=MacOS-Dua


  app3:
    build: ./app
    environment:
      - HOSTNAME=app-container3
      - PLATFORM=MacOS-Sza

  nginx:
    image: nginx:latest
    ports:
       - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3